services:
  spring:
    build:
      dockerfile: docker/java/Dockerfile
    container_name: spring
    depends_on:
      - mongo
    deploy:
      replicas: 1
    expose:
      - 80
    image: task-manager-spring:latest
    networks:
      network:
        aliases:
          - task-manager
    ports:
      - "80:80"

  mongo:
    build:
      dockerfile: docker/mongo/Dockerfile
    container_name: mongo
    deploy:
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    expose:
      - 27017
    image: task-manager-mongo:latest
    networks:
      - network
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

networks:
  network:
    attachable: true
    driver: overlay
