spring:
  application:
    name: task-manager
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/task-manager?authMechanism=SCRAM-SHA-256
      database: task-manager
      authentication-database: task-manager

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000

server:
  port: 8080

logging:
  level:
    root: DEBUG
  file:
    name: application.log
