spring:
  application:
    name: task-manager
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/task-manager?authMechanism=SCRAM-SHA-256
      database: task-manager
      authentication-database: task-manager

jwt:
  secret: 0a8aa3a72b3ac3b3c8e0a6dec37b22320fa0beb87200801f03cf70b6b9a53fa4
  expiration: 3600000

server:
  port: 80

logging:
  level:
    root: DEBUG
